logging:
  pattern:
    console:
      "%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
      %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
  level:
    com.kenny: ERROR

spring:
  datasource:
    hikari:
      auto-commit: false
      data-source-properties:
        # Cache SQL statements
        cachePrepStmts: true
        # Cache size
        prepStmtCacheSize: 250
        # SQL cache length limit
        prepStmtCacheSqlLimit: 2048
        # Server-side prepared statements
        useServerPrepStmts: true
      pool-name: Hikari
    type: com.zaxxer.hikari.HikariDataSource
    # Database connection URL
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    # Database username
    username: { username }
    # Database password
    password: { your password }
  devtools:
    # Disable devtools property addition
    add-properties: false
    # Disable live reload
    livereload:
      enabled: false
    # Disable automatic restart
    restart:
      enabled: false
  h2:
    console:
      # Disable H2 Console
      enabled: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # Disable hibernate's table structure auto-update
      ddl-auto: none
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
    show-sql: false
  profiles:
    active: prod